version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: go-books:latest   # Add this line to tag the image
    container_name: go-books
    expose:
      - "8080"  # This port is used for inter-container communication.
    environment:
      - PORT=8080

  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app