name: Container & Base Image Security Scan

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  security_scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Build the final Go app image.
      - name: Build Go App Container
        run: docker build -t books-app:latest -f Dockerfile .

      # Pull the official NGINX image.
      - name: Pull NGINX Image
        run: docker pull nginx:latest

      # Install Grype for SBOM generation.
      - name: Install Grype
        run: |
          curl -sSfL https://raw.githubusercontent.com/anchore/grype/main/install.sh | sh -s -- -b /usr/local/bin

      # Generate SBOM for the final Go app image.
      - name: Generate SBOM for Go App Container
        run: grype books-app:latest -o cyclonedx > sbom-app.json

      # Generate SBOM for the official NGINX image.
      - name: Generate SBOM for NGINX Container
        run: grype nginx:latest -o cyclonedx > sbom-nginx.json

      # Extract the base image from the dockerfile (ignoring "scratch").
      - name: Extract Base Image from dockerfile
        id: extract_base
        run: |
          if [ ! -f ./Dockerfile ]; then
            echo "Error: dockerfile not found in the repository root."
            exit 1
          fi
          base=$(grep -E '^FROM' ./Dockerfile | awk '{print $2}' | grep -v '^scratch$' | head -n1)
          if [ -z "$base" ]; then
            echo "Error: No valid base image found in dockerfile."
            exit 1
          fi
          echo "Base image found: $base"
          echo "base_image=$base" >> $GITHUB_OUTPUT

      # Pull and generate SBOM for the builder base image.
      - name: Scan Builder Base Image
        run: |
          docker pull "${{ steps.extract_base.outputs.base_image }}"
          grype "${{ steps.extract_base.outputs.base_image }}" -o cyclonedx > sbom-builder.json

      # Upload all SBOM artifacts.
      - name: Upload SBOM Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: sbom-artifacts
          path: |
            sbom-app.json
            sbom-nginx.json
            sbom-builder.json

      # Install Snyk CLI.
      - name: Install Snyk CLI
        run: npm install -g snyk

      # Scan the images directly using Snyk Container Test.
      - name: Run Snyk Container Scan on Go App Image
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        run: snyk container test books-app:latest --json-file-output=snyk-app-container-output.json

      - name: Upload Snyk Go App Container Scan Output
        uses: actions/upload-artifact@v4
        with:
          name: snyk-app-container-scan-output
          path: snyk-app-container-output.json

      - name: Run Snyk Container Scan on NGINX Image
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        run: snyk container test nginx:latest --json-file-output=snyk-nginx-container-output.json

      - name: Upload Snyk NGINX Container Scan Output
        uses: actions/upload-artifact@v4
        with:
          name: snyk-nginx-container-scan-output
          path: snyk-nginx-container-output.json

      - name: Run Snyk Container Scan on Builder Base Image
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        run: snyk container test "${{ steps.extract_base.outputs.base_image }}" --json-file-output=snyk-builder-container-output.json

      - name: Upload Snyk Builder Container Scan Output
        uses: actions/upload-artifact@v4
        with:
          name: snyk-builder-container-scan-output
          path: snyk-builder-container-output.json
