name: Container Security Scan

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  security_scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Go App Container
        run: docker compose build app

      - name: Pull NGINX Image
        run: docker compose pull nginx

      - name: Install Grype
        run: |
          curl -sSfL https://raw.githubusercontent.com/anchore/grype/main/install.sh | sh -s -- -b /usr/local/bin

      - name: Generate SBOM for Go App Container
        run: |
          grype go-books:latest -o cyclonedx > sbom-app.json

      - name: Generate SBOM for NGINX Container
        run: |
          grype nginx:latest -o cyclonedx > sbom-nginx.json

      - name: Upload SBOM Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: sbom-artifacts
          path: |
            sbom-app.json
            sbom-nginx.json

      - name: Install Snyk CLI
        run: npm install -g snyk

      - name: Run Snyk Scan on Go App SBOM
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        run: |
          snyk test --sbom-file=sbom-app.json | tee snyk-app-output.txt

      - name: Upload Snyk Go App Scan Output
        uses: actions/upload-artifact@v4
        with:
          name: snyk-app-scan-output
          path: snyk-app-output.txt

      - name: Run Snyk Scan on NGINX SBOM
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        run: |
          snyk test --sbom-file=sbom-nginx.json | tee snyk-nginx-output.txt

      - name: Upload Snyk NGINX Scan Output
        uses: actions/upload-artifact@v4
        with:
          name: snyk-nginx-scan-output
          path: snyk-nginx-output.txt
